global_params:
  working_dir: cache
  kv_backend: rocksdb # key-value store backend, support: rocksdb, json_kv
  graph_backend: kuzu # graph database backend, support: kuzu, networkx

nodes:
  - id: read_step
    op_name: read
    type: source
    dependencies: []
    params:
      input_path:
        - examples/input_examples/search_reactome_demo.jsonl # input file path, support json, jsonl, txt, pdf. See examples/input_examples for examples

  - id: search_step
    op_name: search
    type: map_batch
    dependencies:
      - read_step # search_step depends on read_step
    execution_params:
      replicas: 1
      batch_size: 10
    save_output: true
    params:
      data_source: reactome # data source for searcher, support: uniprot, ncbi, rnacentral, reactome
      reactome_params:
        species: "Homo sapiens" # species name, support: Homo sapiens, Mus musculus, Rattus norvegicus, etc.
        timeout: 30 # request timeout in seconds
        max_retries: 3 # maximum number of retries for failed requests
